<?php

namespace AppBundle\Repository;

/**
 * GeocodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeocodeRepository extends \Doctrine\ORM\EntityRepository implements GeocodeRepositoryInterface
{
    /**
     * @codeCoverageIgnore
     * {@inheritdoc}
     */
    public function save($location)
    {
        $this->_em->persist($location);
        $this->_em->flush();
    }

    /**
     * {@inheritdoc}
     */
    public function findByAddress($address)
    {
        if (empty($address)) {
            throw new \InvalidArgumentException('Required $address');
        }
        return $this->createQueryBuilder('p')
            ->where('p.search LIKE :search OR p.address LIKE :search')
            ->setParameter('search', $address)
            ->setMaxResults(10)
            ->getQuery()->getResult();

    }
}
