<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Location;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository implements LocationRepositoryInterface
{
    /**
     * @codeCoverageIgnore
     * {@inheritdoc}
     */
    public function save($location)
    {
        $this->_em->persist($location);
        $this->_em->flush();
    }

    /**
     * {@inheritdoc}
     */
    public function findOneByLocation(array $latlng)
    {
        if (!isset($latlng['lat']) || !isset($latlng['lng']) || !is_numeric($latlng['lat']) || !is_numeric($latlng['lng'])) {
            throw new \InvalidArgumentException('Required $latlng i.e. [lat => 11.11, lng => 22.22]');
        }
        return $this->findOneBy($latlng);
    }
}
