<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Place;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository implements PlaceRepositoryInterface
{
    /**
     * @codeCoverageIgnore
     * {@inheritdoc}
     */
    public function save($place)
    {
        $this->_em->persist($place);
        $this->_em->flush();
    }

    /**
     * {@inheritdoc}
     */
    public function findByPlaceId($placeId)
    {
        if (empty($placeId)) {
            throw new \InvalidArgumentException('$placeId required');
        }
        return $this->findOneBy(['placeId' => $placeId]);
    }
}
